name: enderbow
version: '${project.version}'
main: org.enderbow.Enderbow
api-version: '1.20'
load: STARTUP
commands:
  enderbow:
    description: Gives the player an Enderpearl Bow
    usage: /<command>
    permission: enderbow.command.enderbow
    aliases:
      - ebow
    permission-message: "You do not have permission to use this command"
