compass:
  enabled: true  # Whether the compass functionality is enabled
  name: "Server Selector"  # Name displayed in chat messages
  name_color: "GOLD"  # Color code for the name (check Bukkit documentation for color codes)
  play_sound: true  # Whether to play a sound when using the compass
  gui:  # Configuration for the compass GUI
    size: 27  # Number of slots in the GUI
    title: "Server Selector"  # Title displayed in the GUI
    items: # List of items displayed in the GUI (each item requires its own key)
      example_item: # Key for this item
        material: DIAMOND  # Material for the item (check Bukkit documentation for materials)
        name: "%player_name%'s Server"  # Display name of the item with placeholder
        lore: # Lore for the item
           - "This is line 1"
           - "This is line 2 with %some_placeholder%"
        command: "server example"  # Command to execute when the item is clicked (replace "example" with your actual server name)
    messages: # Compass-related chat messages
      compass_give: "You have been given a Compass!"
      no_permission_command: "You do not have permission to use this command!"
      no_permission_use: "You do not have permission to use the Compass!"
      no_console: "Only players can use this command!"