name: SpigotPlugin
version: '1.0-SNAPSHOT'
main: org.caldev.SpigotPlugin
api-version: '1.20'
authors: [ 'Caldev' ]
commands:
  cow:
      description: SpigotPlugin command
      usage: "/cow"
      permission: spigotplugin.command.cow
      permission-message: "You do not have permission to use this command"
  ebow:
      description: Gives the player an Enderpearl Bow
      usage: /<command>
      permission: spigotplugin.command.ebow